homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 645
  unit_system: Metric
  time_zone: America/Edmonton
  customize: !include_dir_merge_named customize
   
frontend:
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password 
  
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

discovery:

conversation:

history:

logbook:

sun:

# Weather Prediction

tts:
  platform: google

zwave:
  usb_path: /dev/ttyACM0


emulated_hue:
  type: google_home
  host_ip: 192.168.1.102
  listen_port: 80
  expose_by_default: true
  exposed_domains:
       - light
       - switch       

light:
  platform: hue
  host: 192.168.1.124

       
switch:
  platform: flux
  lights:  
    - light.chair_light
    - light.couch_light
  name: Fluxer
  start_time: '5:00'
  stop_time: '22:00'
  start_colortemp: 8000
  sunset_colortemp: 2500
  stop_colortemp: 1900
  disable_brightness_adjust: True
  mode: mired

ifttt:
  key: !secret ifttt

media_player:
  - platform: roku
#  - platform: plex
  
zone: !include zones.yaml
group: !include groups.yaml
device_tracker: !include device_trackers.yaml
automation: !include_dir_list automation
script: !include_dir_merge_named scripts
scene: !include_dir_list scenes
weblink: !include weblink.yaml
sensor: !include_dir_merge_list sensor