homeassistant:
  name: Home
  latitude: !secret latitude 
  longitude: !secret longitude
  elevation: 645
  unit_system: Metric
  time_zone: America/Edmonton
  customize: !include_dir_merge_named customize

# Show links to resources in log and frontend


# Enables the frontend
frontend:

http:
  api_password: !secret api_password 


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
#history:

# View all events in a logbook
logbook:

# Track the sun
sun:

script: !include_dir_merge_named scripts
scene: !include_dir_list scenes
group: !include group.yaml
automation: !include_dir_list automation
device_tracker: !include device_trackers.yaml
zone: !include zones.yaml
sensor: !include sensor.yaml
weblink: !include weblink.yaml

media_player:
  - platform: roku
  - platform: plex


emulated_hue:
  type: google_home
  host_ip: 192.168.1.102
  listen_port: 80
  expose_by_default: true
  exposed_domains:
    - light
    - switch

ifttt:
  key: !secret ifttt

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 30000

