######
#TABS#
######
default_view:
  name: Home
  icon: mdi:home-assistant
  view: yes
  entities:
    - group.family
    - group.lights
    - group.scenes
  
room_lights:
  name: All Ligths
  icon: mdi:lightbulb-on
  view: yes
  entities:
    - group.kitchen_lights
    - group.bedroom_lights
    - group.foyer_lights
    - group.living_room_lights
    - group.outdoor_lights
    - group.light_usage

weather:
  name: Weather
  icon: mdi:cloud-outline
  view: yes
  entities:
    - group.weather_2
    - group.basement_climate
 
media_players:
  name: Media
  icon: mdi:filmstrip
  view: yes
  entities:
    - group.media
 
network_status:
  name: Network Status
  icon: mdi:server-network
  view: yes
  entities:
    - group.internet_status
    - group.network

system_status:
  name: System Status
  icon: mdi:pulse
  view: yes
  entities:
    - group.system
    - group.ha_stats
  
automation:
  name: Automation Override
  icon: mdi:settings
  view: yes
  entities:
    - automation.turn_off_all_room_lights__12am
    - automation.garage_lights_on_arrival
    - automation.turn_on_porch_light_when_sun_sets
    - automation.turn_off_porch_lights_off_at_10pm
    - automation.porch_lights_on_arrival
    - group.automation_switch  
    
########
#Groups#
########

Family:
  - device_tracker.anniesphone
  - device_tracker.phone_robb_
  
Lights:
  - group.foyer_lights
  - group.living_room_lights
  - group.outdoor_lights
  - group.kitchen_lights
  - group.bedroom_lights
  - switch.leviton_dzpa11lw_plugin_appliance_module_switch_2_0
  
Kitchen Lights:
  - light.leviton_unknown_type1b03_id0334_level_3_0
  
Living Room Lights:
  - light.chair_light
  - light.couch_light
  
Outdoor Lights:
  - light.garage_light_left
  - light.garage_light_right
  - light.porch_light
  
Garage Lights:
  - light.garage_light_left
  - light.garage_light_right
  
Foyer Lights:
  - light.coat_rack
  
Bedroom Lights:
  - light.anatheas_light
  - light.robbs_light
  
Scenes:
  - scene.movie_time
  - scene.bright
  
Internet Status:
  - sensor.speedtest_ping
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - weblink.router

System:
  - sensor.cpu_use
  - sensor.disk_use_
  - sensor.ram_free
  - sensor.received_eth0
  - sensor.sent_eth0
  - sensor.last_boot
  - automation.restart_hass


Weather:
  - sensor.pws_weather
  - sun.sun
  - sensor.pws_temp_c
  - sensor.pws_feelslike_c
  - sensor.pws_relative_humidity
  - sensor.pws_wind_kph
  - sensor.pws_wind_dir
  - sensor.pws_precip_today_metric
  
Media:
  - media_player.roku_3__1gs3d9081111
  - media_player.roku_3__1gn39j219073
  - media_player.roku_1gs3d9081111  
  - media_player.roku_1gn39j219073
  - media_player.galaxy_s5
  - media_player.garage
  - media_player.kitchen_home
  - sensor.plex
  - weblink.new_media_report
  
Automation Switch:
   - switch.fluxer
   
Basement Climate:
   - sensor.sn1_humidity
   - sensor.sn1_temperature 
   - sensor.sn1_ldr

Network:
   - sensor.htpc
   - sensor.chromecast
   - sensor.a47733efd28c
   - sensor.np1gn39j219073
   
Light Usage:
    - sensor.kitchen_history
    - sensor.living_room_history
    - sensor.bedroom_lights
    - sensor.garage_lights
    
HA Stats:
    - sensor.home_assistant_installed_version
    - sensor.home_assistant_uptime