alias: Turn on Air Conditioner
initial_state: True
trigger:
  - platform: template
    value_template: '{{ states.sensor.sn1_temperature.state | float >= 24}}'
condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'on'
  - condition: time
    after: '9:00:00'
    before: '22:00:00'
action:
  - service: switch.turn_on
    entity_id: switch.leviton_dzpa11lw_plugin_appliance_module_switch


