alias: Turn Off Air Conditioner
trigger:
  - platform: numeric_state
    entity_id: sensor.sn1_temperature
    below: 22
 
action:
  - service: switch.turn_off
    entity_id: switch.leviton_dzpa11lw_plugin_appliance_module_switch