alias: "Mark Annie Away"
condition:
  condition: state
  entity_id: input_boolean.annie_home    
  state: 'on'
# Will only trigger if all are 'not_home'
trigger:
  platform: template
  value_template: "{% if (is_state('device_tracker.anniesphone','not_home')) and (is_state('device_tracker.annies_phone','not_home')) %}true{% endif %}"
action:
  service: homeassistant.turn_off
  entity_id: input_boolean.annie_home