alias: "Mark Robb Away"
condition:
  condition: state
  entity_id: input_boolean.robb 
  state: 'on'
# Will only trigger if all are 'not_home'
trigger:
  platform: template
  value_template: "{% if (is_state('device_tracker.robb_parker_galaxy_s5','not_home')) and (is_state('device_tracker.phone_robb_','not_home')) %}true{% endif %}"
action:
  service: homeassistant.turn_off
  entity_id: input_boolean.robb