alias: Turn on Living Room light at sunset
trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"       
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.presence_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
action:
  - service: light.turn_on
    entity_id: group.living_room_lights
    data:
      brightness: 255
  - service: script.speech_engine
    data:
      call_dark_outside: 1
