alias: 'Porch Lights on Arrival'
trigger:
  platform: state
  entity_id: input_boolean.annie_home, input_boolean.robb_home
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state                      
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state                  
      entity_id: light.porch_light
      state: 'off'
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
action:
  service: light.turn_on
  entity_id: light.porch_light


