alias: Turn on Porch light when sun sets
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: state
  entity_id: group.input_boolean_presence
  state: 'on'
action:
  service: light.turn_on
  entity_id: light.porch_light

