################################################################################
## The outside temp has dropped below the inside temp, open some some windows ##
################################################################################
alias: 'Open Windows'
trigger:
  - platform: template
    value_template: '{{ (states("sensor.pws_temp_c") | float) < (states("sensor.sn1_temperature") | float) }}'
condition:
  - condition: state
    entity_id: input_boolean.presence
    state: 'on'
action:
  - service: script.speech_engine
    data:
      call_temp_outside: 1
      
