- platform: template
  sensors:
    htpc:
      value_template:  '{% if is_state("device_tracker.htpc", "home") %} Online {% else %} Offline {%- endif %}'

- platform: template
  sensors:
    chromecast:
      value_template:  '{% if is_state("device_tracker.chromecast", "home") %} Online {% else %} Offline {%- endif %}'
      
- platform: template
  sensors:
    a47733efd28c:
      value_template:  '{% if is_state("device_tracker.a47733efd28c", "home") %} Online {% else %} Offline {%- endif %}'
      
- platform: template
  sensors:
    np1gn39j219073:
      value_template:  '{% if is_state("device_tracker.np1gn39j219073", "home") %} Online {% else %} Offline {%- endif %}'