###############################
#Bruh Senssor Node Lily's Room#
###############################
- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  

- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 Temperature"  
  unit_of_measurement: "°C"  
  value_template: '{{ value_json.temperature | round(1) }}'  
  
- platform: mqtt  
  state_topic: "bruh/sensornode1"  
  name: "SN1 LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'    
  
  
  
###############################
#Bruh Senssor Node Evan's Room#
###############################