- platform: wunderground
  api_key: !secret wunderground
  monitored_conditions:
    - weather
    - wind_kph
    - temp_c
    - wind_dir
    - relative_humidity
    - feelslike_c
    - precip_today_metric
    
    
