alias: 'Garage Lights on Arrival'
trigger:
  platform: state
  entity_id: device_tracker.anniesphone, device_tracker.phone_robb_
  from: 'not_home'
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.outdoor_lights
      state: 'off'
action:
  service: homeassistant.turn_on
  entity_id: "script.get_home_sunset"


