alias: 'Porch Lights on Arrival'
trigger:
  platform: state
  entity_id: device_tracker.anniesphone, device_tracker.phone_robb_
  from: 'not_home'
  to: 'home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.porch_light
      state: 'off'
    - condition: state
      entity_id: input_boolean.automation_override
      state: 'off'
action:
  service: light.turn_on
  entity_id: light.porch_light


